### ISSUE TITLE
Running on system with multiple GPU fails (ddp failure)

### ISSUE THREAD

**Issue by koush** [WongKinYiu/YOLO#119]
## Describe the bug
Running on system with multiple GPU fails.

## To Reproduce
Setup system with 2 GPUs.

Run the training command:

```sh
python yolo/lazy.py task=train dataset=coco use_wandb=True

Error executing job with overrides: ['task=train', 'dataset=coco', 'use_wandb=True']
Traceback (most recent call last):
  File "/home/koush/yolov9mit/YOLO/yolo/lazy.py", line 35, in main
    trainer.fit(model)
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 46, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 1023, in _run_stage
    self._run_sanity_check()
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 1052, in _run_sanity_check
    val_loop.run()
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 128, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
                                       ^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
            ^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/lightning/pytorch/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/.venv/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/koush/yolov9mit/YOLO/yolo/tools/data_loader.py", line 207, in collate_fn
    batch_images = torch.stack(batch_images)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects each tensor to be equal size, but got [3, 256, 1024] at entry 0 and [3, 416, 864] at entry 16

```

## Expected behavior
Training proceeds.

## System Info (please complete the following ## information):
 - OS: [e.g. Ubuntu 20.04] 22.04
 - Python Version: [e.g. 3.8] 3.10
 - PyTorch Version: [e.g. 1.8.1]2.5.1
 - CUDA/cuDNN/MPS Version: [e.g. CUDA 11.1] 12.6
 - YOLO Model Version: [e.g. YOLOv9-c] 9c

## Additioal Nodes
Modifying lazy.py to use num_devices=1, num_nodes=1 works as expected. DDP is failing.

**Comment by henrytsui000** [comment]
Hi,

Could you please tell me your Git commit version? I recently fixed a very similar issue in commit 309271089a6f916197e4e7977f77738ba1521bfb.

Best regards,
Henry Tsui

**Comment by koush** [comment]
```
commit 2522f723d0db5c72a6e49a7331b844290ef0af34 (HEAD -> main, origin/main, origin/TEST, origin/HEAD)
Author: henrytsui000 <henrytsui000@gmail.com>
Date:   Tue Nov 5 14:43:04 2024 +0800

    ✅ [Pass] test in multiclass label&dynamic shape

```

**Comment by koush** [comment]
Updated to 959b9b05667f6b9a1f349bc2c9843d039e405f60, issue persists.

**Comment by henrytsui000** [comment]
Hi,  

Can you try turning off the `dynamic_shape` setting in `yolo/config/task/validation.yaml`? You can do this by modifying the configuration as follows:  
```yaml
task: validation

data:
  ...
  dynamic_shape: False
...
```  

Alternatively, you can disable it during training with the following command:  
```bash
python yolo/lazy.py task=train ... task.validation.data.dynamic_shape=False
```  

I suspect the issue is caused by the sampler and the `dynamic_shape` setting. Turning it off will disable the auto-adjustment of the input shape in the validation phase. While this might result in a slightly lower mAP, it will enable multiple GPU validation.  

If you need a higher-performance model, you can perform validation after training using a single GPU after training—or you can wait for me to find time to fix this properly.  

Best regards,  
Henry Tsui

**Comment by koush** [comment]
That extra command line parameter seems to have suppressed the issue.

**Comment by koush** [comment]
Training completes 1 epoch, performs the validation step seemingly with no error, and then hangs.
