### ISSUE TITLE
cant run transfer learning for v7 model

### ISSUE THREAD

**Issue by ksv87** [WongKinYiu/YOLO#131]
cant run transfer learning for v7 model

`python yolo/lazy.py task=train task.data.batch_size=8 model=v7 dataset=test_dataset device=cuda use_wandb=False use_tensorboard=True name=v7-dev`

get error

```
Error executing job with overrides: ['task=train', 'task.data.batch_size=8', 'model=v7', 'dataset=test_dataset', 'device=cuda', 'use_wandb=False', 'use_tensorboard=True', 'name=v7-dev']
Traceback (most recent call last):
  File "/home/ksv/YOLO/yolo/lazy.py", line 34, in main
    trainer.fit(model)
  File "/home/ksv/miniconda3/envs/yolox/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/home/ksv/miniconda3/envs/yolox/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ksv/miniconda3/envs/yolox/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/ksv/miniconda3/envs/yolox/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 943, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/home/ksv/miniconda3/envs/yolox/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 104, in _call_setup_hook
    _call_lightning_module_hook(trainer, "setup", stage=fn)
  File "/home/ksv/miniconda3/envs/yolox/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 167, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/ksv/YOLO/yolo/tools/solver.py", line 84, in setup
    self.loss_fn = create_loss_function(self.cfg, self.vec2box)
  File "/home/ksv/YOLO/yolo/tools/loss_functions.py", line 140, in create_loss_function
    loss_function = DualLoss(cfg, vec2box)
  File "/home/ksv/YOLO/yolo/tools/loss_functions.py", line 112, in __init__
    self.loss = YOLOLoss(loss_cfg, vec2box, class_num=cfg.dataset.class_num, reg_max=cfg.model.anchor.reg_max)
omegaconf.errors.ConfigAttributeError: Missing key reg_max
    full_key: model.anchor.reg_max
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by ksv87** [comment]
@henrytsui000 hello, help, please

**Comment by chao-camect** [comment]
I just met the same problem. Looks like the code only works with yolo9, not tested with yolo7

**Comment by marcivanmanalac** [comment]
Hello,

I am also trying to solve this problem.

**Comment by Hiram31** [comment]
Same here. Failed to run for yolov7.

**Comment by colintoal** [comment]
This framework does not seem to have the Yolo v7 Loss metrics code implemented. It has the 3 metrics that are specific to v9 - but it does not have an implementation for the loss metrics needed for v7
