### ISSUE TITLE
Missed keys during inference

### ISSUE THREAD

**Issue by fronos** [WongKinYiu/YOLO#136]
## Describe the bug
I'm trained custom model Yolo v9-m from scratch. During inference I noticed that logger throwing messages:
```
WARNING  ⚠ Weight Not Found for key: 19.conv                                                                                                                                      yolo.py:152
WARNING  ⚠ Weight Not Found for key: 21.conv3.0.conv2                                                                                                                             yolo.py:152
WARNING  ⚠ Weight Not Found for key: 34.conv3.0.conv2                                                                                                                             yolo.py:152
WARNING  ⚠ Weight Not Found for key: 38.heads.1.anchor_conv.0                                                                                                                     yolo.py:152
WARNING  ⚠ Weight Not Found for key: 22.heads.2.anc2vec  
```
The main reasons of this warnings:  
1. Lightning save weights as a key of file with extension .ckpt. 
2. Keys of initialized model and trained model mismatched. Need add model.model into name of key

## System Info (please complete the following ## information):
 - OS: [e.g. Ubuntu 20.04]
 - Python Version: 3.10.16
 - PyTorch Version: 2.5.1
 - Lightning: 2.4.0
 - CUDA/cuDNN/MPS Version: 12.4
 - YOLO Model Version: YOLOv9-m

**Comment by cansik** [comment]
I have the same issue here for a custom YOLOv9-t model. Basically, the custom trained checkpoint won't be able to load for inference. What I've done is adjusting the `create_model` method in yolo.py to allow to read ckpt files. This seems to work!

```python
def create_model(model_cfg: ModelConfig, weight_path: Union[bool, Path] = True, class_num: int = 80) -> YOLO:
    """Constructs and returns a model from a Dictionary configuration file.

    Args:
        config_file (dict): The configuration file of the model.

    Returns:
        YOLO: An instance of the model defined by the given configuration.
    """
    OmegaConf.set_struct(model_cfg, False)
    model = YOLO(model_cfg, class_num)
    if weight_path:
        if weight_path == True:
            weight_path = Path("weights") / f"{model_cfg.name}.pt"
        elif isinstance(weight_path, str):
            weight_path = Path(weight_path)

        if not weight_path.exists():
            logger.info(f"🌐 Weight {weight_path} not found, try downloading")
            prepare_weight(weight_path=weight_path)
        if weight_path.exists():
            if weight_path.suffix == ".ckpt":
                checkpoint = torch.load(weight_path)
                state_dict = checkpoint['state_dict']

                # Fix the keys in the checkpoint
                new_state_dict = {}

                for key, value in state_dict.items():
                    if key.startswith("model.model."):
                        new_key = key.replace("model.model.", "model.", 1)
                        new_state_dict[new_key] = value
                    else:
                        new_state_dict[key] = value

                # Load new state dict
                model.load_state_dict(new_state_dict, strict=False)

                for name, param in model.named_parameters():
                    if name not in new_state_dict:
                        print(f"Missing weight for layer: {name}")

                logger.info(":white_check_mark: Success load model & checkpoint")
            else:
                model.save_load_weights(weight_path)
                logger.info(":white_check_mark: Success load model & weight")
```

**Comment by divyanidhi** [comment]
@cansik Can you please share your run command for inferencing?

**Comment by sberkson** [comment]
@cansik I am also having trouble here.  Implementing your fix to the 'create_model' function results in an error being thrown:

 Error executing job with overrides: ["weight='runs/train/v9-dev/YOLO/fq5v6o9s/checkpoints/epoch=4-step=1590.ckpt'"]
Traceback (most recent call last):
  File "YOLO/yolo/lazy.py", line 41, in main
    model = InferenceModel.load_from_checkpoint(cfg.weight, cfg=cfg)
  File "YOLO/venv/lib/python3.10/site-packages/lightning/pytorch/utilities/model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "YOLO/venv/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 1581, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "YOLO/venv/lib/python3.10/site-packages/lightning/pytorch/core/saving.py", line 91, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "YOLO/venv/lib/python3.10/site-packages/lightning/pytorch/core/saving.py", line 165, in _load_state
    obj = instantiator(cls, _cls_kwargs) if instantiator else cls(**_cls_kwargs)
  File "YOLO/yolo/tools/solver.py", line 112, in __init__
    super().__init__(cfg)
  File "YOLO/yolo/tools/solver.py", line 19, in __init__
    self.model = create_model(cfg.model, class_num=cfg.dataset.class_num, weight_path=cfg.weight)
  File "YOLO/yolo/model/yolo.py", line 197, in create_model
    model.load_state_dict(new_state_dict, strict=False)
  File "YOLO/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2581, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for YOLO:
        size mismatch for model.22.heads.0.class_conv.2.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for model.22.heads.0.class_conv.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for model.22.heads.1.class_conv.2.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for model.22.heads.1.class_conv.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for model.22.heads.2.class_conv.2.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for model.22.heads.2.class_conv.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for model.30.heads.0.class_conv.2.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for model.30.heads.0.class_conv.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for model.30.heads.1.class_conv.2.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for model.30.heads.1.class_conv.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
        size mismatch for model.30.heads.2.class_conv.2.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 128, 1, 1]).
        size mismatch for model.30.heads.2.class_conv.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).

I successfully trained a model and obtained a .ckpt file, but have been unable to load the weights for inference.  The furthest I've gotten is having 0 predictions instead of predictions for some of the 80 classes contained in the base model.

Do you have any further changes you implemented that were not described above?  Further guidance would be very much appreciated.
